JobMining/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts', include('allauth.urls')),
    path('', include('mining.urls', namespace='mining')),
]

mining/urls.py
from django.conf.urls import url
from django.urls import path, include
from markdownx import urls as markdownx

from .views import advert_list, advert_detail, ActionListView, AdvertListView

app_name = 'mining'
urlpatterns = [
    path('', AdvertListView.as_view(), name='advert_list'),   # advert_list, name='advert_list'),
    path('<uuid:advert_id>/', advert_detail, name='advert_detail'),
    path('actions/', ActionListView.as_view(), name='all_action_list'),

    url(r'^markdownx/', include(markdownx)),
]

mining/models.py
import uuid
from django.contrib.auth import get_user_model
from django.db import models
from markdownx.models import MarkdownxField
import logging

logger = logging.getLogger(__name__)


class Activity(models.Model):
    timestamp = models.DateTimeField(auto_now_add=True)
    advert = models.ForeignKey('Advert', models.DO_NOTHING, related_name='actions')
    action = models.TextField('Действие')
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE
    )

    class Meta:
        db_table = 'activity'
        verbose_name_plural = 'actions'

    def __str__(self):
        return f"{self.action}"


class Advert(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False)
    organization = models.CharField(max_length=60)
    post = models.CharField(max_length=60)
    text = MarkdownxField()
    salary = models.CharField(max_length=60, blank=True, null=True)
    person = models.CharField(max_length=60)
    phone = models.CharField(max_length=60)
    pub_date = models.DateField(blank=True, null=True)
    status = models.BooleanField()

    class Meta:
        db_table = 'advert'
        ordering = ('-pub_date',)

    def __str__(self):
        return f"{self.organization}. {self.post}"


    # def save(self, force_insert=False, force_update=False, using=None,
    #          update_fields=None):
    #     """
    #     При создании объявления добавить действие 'Объявление размещено в БД.'
    #     """
    #     Activity.objects.create(advert=self, action='Объявление размещено в БД.',
    #                             author=get_user_model().objects.get(pk=1))
    #     self.status = True
    #     super(Advert, self).save()
    #

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    pass

mining/forms.py
from django import forms

from .models import Activity


class ActionForm(forms.ModelForm):
    class Meta:
        model = Activity
        fields = ('action', )

users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'username',)


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'username',)

mining/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView

from .forms import ActionForm
from .models import Advert, Activity
import logging
import sys

logger = logging.getLogger()
logger.exception(f'{str(sys.executable)}')


class AdvertListView(ListView):
    model = Advert
    template_name = 'mining/advert_list.html'
    context_object_name = 'all_advert_list'
    ordering = ('-pub_date', )

    def get_queryset(self):
        return Advert.objects.filter(status=True)


class ActionListView(ListView):
    model = Activity
    context_object_name = 'all_action_list'
    template_name = 'mining/action_list.html'

    def get_queryset(self):
        return Activity.objects.order_by('-timestamp')[:15]


class AdvertDetailView(DetailView):
    model = Advert


def advert_list(request):
    all_advert_list = Advert.objects.order_by('-pub_date')
    context = {'all_advert_list': all_advert_list}
    return render(request, 'mining/advert_list.html', context)


def advert_detail(request, advert_id):
    advert = get_object_or_404(Advert, pk=advert_id)
    actions = advert.actions.all()
    new_action = None

    if request.method == 'POST':
        # A new action was added
        action_form = ActionForm(data=request.POST)
        if action_form.is_valid():
            # Create action object, but don't save to database yet.
            new_action = action_form.save(commit=False)
            # Assign the current advert to the action
            new_action.advert = advert
            new_action.author = request.user
            # save the action to database
            new_action.save()
    else:
        action_form = ActionForm()
    return render(request, "mining/advert_detail.html",
                  {'advert': advert,
                   'actions': actions,
                   'new_action': new_action,
                   'action_form': action_form})

users/views.py
from django.shortcuts import render

# Create your views here.

mining/templates/mining/action_list.html
{% extends 'mining/base.html' %}
{% load auth_extras %}

{% block title %}
    All actions
{% endblock title %}

{% block content %}
    {% if all_action_list %}
        <h2>Ваши последние действия</h2>
        <div class="all-actions">
            {% for action in all_action_list %}
                {% if user == action.author or user|has_group:"Администраторы" %}
                    <p><b><i>{{ action.timestamp }}</i></b> <a
                            href="{% url 'mining:advert_detail' action.advert.id %}">{{ action.advert.organization }}. {{ action.advert.post }}</a>. {{ action.action }}
                    </p>
                {% endif %}
            {% endfor %}
        </div>
    {% else %}
        <p>Вы еще не совершили ни одного действия.</p>
    {% endif %}
{% endblock content %}

mining/templates/mining/advert_detail.html
{% extends 'mining/base.html' %}
{% load mining_tags %}
{% load crispy_forms_tags %}
{% load auth_extras %}

{% block title %}
    Adverts
{% endblock title %}

{% block content %}
    <div>
        <h1>{{ advert.organization }}. {{ advert.post }}</h1>
        <p>{{ advert.text|markdown }}</p>
    </div>

    <div>
        Оплата: {{ advert.salary }}
    </div>

    <div>
        Объявление опубликовано: {{ advert.pub_date }}
    </div>
    <div>
        Контакы: <strong>{{ advert.phone }}</strong> {{ advert.person }}
    </div>
    <hr>
    <h4>Действия по объявлению:</h4>
    <div class="adverts-actions">
        {% for action in actions %}
            {% if user == action.author or user|has_group:"Администраторы" %}
                <p><i><b>{{ action.timestamp }}</b>. {{ action.author }}: </i>{{ action.action }}</p>
            {% endif %}
        {% endfor %}
    </div>
    <hr>
    <div>
        {% if new_action %}
            <h4>Действие добавлено.</h4>
        {% else %}
            <h4>Добавить новое действие:</h4>

            <form action="." method="post">
                {{ action_form | crispy }}
                {% csrf_token %}
                <p>
                    <button type="submit" class="btn btn-primary">Добавить</button>
                </p>
            </form>
        {% endif %}
    </div>
        <p><a href="{% url 'mining:advert_list' %}">К списку объявлений</a></p>
    </div>
{% endblock content %}

mining/templates/mining/advert_list.html
{% extends 'mining/base.html' %}
{% block title %}
    Adverts
{% endblock title %}
{% block content %}
    <div>
        <h2>Активные объявления</h2>
        {% if all_advert_list %}
            <ul>
                {% for advert in all_advert_list %}
                    <li>
                        <a href="{% url 'mining:advert_detail' advert.id %}">{{ advert.organization }}. {{ advert.post }}</a>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>Нет ни одного объявления.</p>
        {% endif %}
    </div>
{% endblock content %}

mining/templates/mining/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock title %}</title>
    {% load static %}
    {% load mining_tags %}
    {% load crispy_forms_tags %}
    {% load auth_extras %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
<div style="color: #ff0000">
    <h1>Jobmining</h1>
</div>

<div style="font-size: x-small">
    {% if user.is_authenticated %}
        Здравствуйте, <b>{{ user.username }}!</b> <a href="{% url 'mining:all_action_list' %}">Смотреть все действия</a>
        {#        {% if request.user|has_group:"Администраторы" %}#}
        {#            (Администратор)!#}
        {#        {% endif %}#}
        <p><a href="{% url 'account_logout' %}">Выйти</a></p>
    {% else %}
        Вы <b>НЕ</b> авторизованы
        <p>{% url 'account_login' %}</p>
        <p><a href="{% url 'account_login' %}">Авторизоваться</a></p>
    {% endif %}
</div>

<div class="container-fluid">
    {% block content %}
    {% endblock content %}
</div>
</body>
</html>